version: '3.8'
services:
  billtitlesapi:
    image: docker.io/arihersh/billtitles:latest
    container_name: billtitleapi 
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      #POSTGRES_URL: postgresql://postgres:pg_db@postgresql:5432/postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 8000:8000
    depends_on:
      - postgresql
  pg_db:
    container_name: pg_db
    image: docker.io/arihersh/billsim-pgsql:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: