:toc:

# BillSim: Utilities to process similarity of bills

This repository extracts the bill similarity functions from the BillMap project https://github.com/unitedstates/BillMap[here]. Both are open source, under the Public Domain License.  

A separate repository (github.com/aih/bills) contains tools in Go to process bill data.

## Processing bill XML files

The default functions assume that the bill XML files are in a directory three levels up from the `billsim/utils.py`  file, of the form `congress/data/`.

Then you can run the following command to process all the bill XML files in the directory:

```python
>>> from billsim.utils import getBillXmlPaths
>>> z=getBillXmlPaths()
>>> z[30]
BillPath(billnumber_version='116hr1818ih', path='.../billsim/congress/data/116/bills/hr1818/BILLS-116hr1818ih.xml', fileName='BILLS-116hr1818ih.xml')
```

## Creating Elasticsearch index of bill sections 

Install Elasticsearch (>=7.0.0 and <7.10.2) and run the following commands to create the index:

```python
>>> from billsim.elastic_load import initializeBillSectionsIndex
>>> initializeBillSectionsIndex()
```

This will gather all of the bill paths in the directory specified in .env and create an Elasticsearch index with the name specified in .env (or the default in constants). Creating the index will take approximately 5 minutes per Congress directory on a reasonably fast server (e.g. 16GB ram, 3 GHz), without any concurrent processing or other optimizations (e.g. using ).

NOTE: This will not delete the index if it already exists. To do so, and start over, pass `delete=True` to `billsim.elastic_load.createIndex`.

NOTE: The Elasticsearch versions after 7.10.2 are forked between the full 'OSS' version and a more restrictive license (as a challenge to Cloud services like AWS). The python client library must match the version of the Elasticsearch server.